server:
  port: 0
spring:
  application:
    name: api-provider
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/checkAgro-dev
    username: usr-checkAgro
    password: pwd-checkAgro
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true